### ISSUE TITLE
[Bug]:  GROUP STUCK WHEN RESIZE AT NEGATIVE VALUE

### ISSUE THREAD

**Issue by 4lt3r3go** [Comfy-Org/ComfyUI_frontend#1486]
### Frontend Version

-

### Expected Behavior

-

### Actual Behavior

-

### Steps to Reproduce

-

### Debug Logs

```powershell
-
```

### Browser Logs

-

### Setting JSON

-

### Other

i used to add some
https://github.com/user-attachments/assets/d189805d-cb26-4183-8e62-01f5eba4cb36
text in the workflow, by just adding empty groups and give them some text.
when resizing the group bar like showed in the video the group stuck and is impossible to remove/resize/move.
they are just sitting there forever.
I was able to remove the ghost groups only by edit the json in a notepad

**Comment by huchenlei** [comment]
Already fixed in latest version (v1.3.37)

**Comment by 4lt3r3go** [comment]
uhm i installed comfy portable yesterday and the problem is still here. 
anyway i can live with this, just trying to give my poor contribute in bug reports

**Comment by LukeG89** [comment]
@4lt3r3go The problem is still there because the latest frontend has not been officially released in ComfyUI yet.

To use the latest frontend, you need to add this command line argument in your `run_nvidia_gpu.bat` file (next to `--windows-standalone-build`)

```
--front-end-version Comfy-Org/ComfyUI_frontend@latest
```
