### ISSUE TITLE
[Bug]: Freeze UI even after clean install and no custom nodes

### ISSUE THREAD

**Issue by sirolim** [Comfy-Org/ComfyUI_frontend#1600]
### Frontend Version

1.3.26

### Expected Behavior

ComfyUI should load normally. The nodes and splines should be displayed normally. Nodes should load nomally.

### Actual Behavior

When I load the default workflow it looks like this.

When I drop in a workflow it also doesnt load the nodes and splines correctly.
I can't move or zoom within the UI.

### Steps to Reproduce

It neither works in Stability Matrix nor portable ComfyUI.
After a clean install of Stability Matrix I'm not able to install the ComfyUI package. It fails during the install.

It seems like there is some global python issue. So I reinstalled globally python 3.10.9.
The problem still remains. My second guess there is a problem to create venv.

### Debug Logs

```powershell
The Log from a clean installed ComfyUI_portable:

C:\Tools\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
Total VRAM 24576 MB, total RAM 65424 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: C:\Tools\ComfyUI_windows_portable\ComfyUI\web
C:\Tools\ComfyUI_windows_portable\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)

Import times for custom nodes:
   0.0 seconds: C:\Tools\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py

Starting server

To see the GUI go to: http://127.0.0.1:8188
```

### Browser Logs

![Screenshot 2024-11-17 203959](https://github.com/user-attachments/assets/91c75b36-82b1-4250-a8bd-237c902f7481)

### Setting JSON

{
    "Comfy.ColorPalette": "custom_milk_white",
    "Comfy.LinkRenderMode": "2"
}

**Comment by sirolim** [comment]
the problem was here
"Comfy.ColorPalette": "custom_milk_white",

after changing the line to:
"Comfy.ColorPalette": "dark",

ComfyUI Portable was fixed.

ComfyUI package install in Stability Matrix is still failing during install.

**Comment by huchenlei** [comment]
v1.3.26 is not goind to be maintained. The issue has been fixed in https://github.com/Comfy-Org/ComfyUI_frontend/pull/1487

**Comment by sirolim** [comment]
Sorry maybe the last sentence was not clear, the package install in Stability Matrix is still failing. But that might be also a Stability Matrix problem.
