### ISSUE TITLE
[Bug]: Incorrect Node Stacking when Loading Workflow

### ISSUE THREAD

**Issue by brucew4yn3rp** [Comfy-Org/ComfyUI_frontend#1747]
### Frontend Version

1.3.44

### Expected Behavior

When loading a workflow, nodes should load in the same layout they are in when saved,

### Actual Behavior

Nodes that should be "hidden" behind other nodes always load on top.

![image](https://github.com/user-attachments/assets/6c5f73f8-5528-4382-957e-cd054504d709)

### Steps to Reproduce

[Node Stacking Test.json](https://github.com/user-attachments/files/17964151/Node.Stacking.Test.json)

### Debug Logs

```powershell
N/A
```

### Browser Logs

N/A

### Setting JSON

[comfy.settings.json](https://github.com/user-attachments/files/17964153/comfy.settings.json)

### What browsers do you use to access the UI ?

Google Chrome

**Comment by webfiltered** [comment]
Hi there, your settings indicate you have the below setting enabled.  This setting re-orders nodes by their ID when saving a workflow.  Disabling it should resolve the issue.

```
Comfy.Workflow.SortNodeIdOnSave
```
![image](https://github.com/user-attachments/assets/a9cd77b4-77a7-4f48-b70b-dce441f84677)

**Comment by brucew4yn3rp** [comment]
Hi @webfiltered. The issue still occurs when Sort Node IDs is disabled. In fact, I only turned on that option to try and resolve the error. This was not an issue with the old Comfy frontend.

**Comment by brucew4yn3rp** [comment]
Following up here - changing this setting to 'Manual Drag & Drop' seems to fix the issue.

![image](https://github.com/user-attachments/assets/8afb6640-6791-4a5c-86fc-b4b87439097a)
