### ISSUE TITLE
Run button disabled saying workflow contains unsupported nodes if anything except core nodes are in workflow.

### ISSUE THREAD

**Issue by GroxicTinch** [Comfy-Org/ComfyUI_frontend#6766]
### Prerequisites

- [x] I am running the latest version of ComfyUI
- [x] I have searched existing issues to make sure this isn't a duplicate
- [x] I have tested with all custom nodes disabled ([see how](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled))

### What happened?

The following cause the Run button to be disabled.
- Create new tab
- Open workflow
- Change tab to a workflow that is either empty or contains any custom node

The run button also doesn't update if it is available until you change to a different tab and come back or reload the page.

Workflows with custom nodes can be run by copy and pasting all the nodes into a currently enabled tab but tabbing away and back will break it.

Even without custom nodes installed then creating a new tab and building a workflow only works after creating a second tab to temporarily open.

### Steps to Reproduce

1. Load\Create a workflow with core nodes only
2. Add a custom node to working workflow(even if not connected)
3. Create a second tab
4. Change back to workflow tab and it is no longer enabled.

<img width="1235" height="473" alt="Image" src="https://github.com/user-attachments/assets/a897b644-37cf-477f-8a9f-5bf7a80891b5" />

<img width="1235" height="473" alt="Image" src="https://github.com/user-attachments/assets/a453563f-4363-434c-8d6f-437e9574fbf5" />

### How is this affecting you?

Workflow won't execute

### ComfyUI Frontend Version

1.33.1

### Browser

Firefox

### Console Errors

```javascript
No errors but following warnings

Invalid URI. Load of media resource  failed. 2 127.0.0.1:8188
[ComfyUI Notice] "scripts/widgets.js" is an internal module, not part of the public API. Future updates may break this import. widgets.js:2:9
[ComfyUI Notice] "scripts/pnginfo.js" is an internal module, not part of the public API. Future updates may break this import. pnginfo.js:2:9
[ComfyUI Notice] "extensions/core/clipspace.js" is an internal module, not part of the public API. Future updates may break this import. clipspace.js:2:9
[ComfyUI Notice] "scripts/utils.js" is an internal module, not part of the public API. Future updates may break this import. utils.js:2:9
[ComfyUI Deprecated] Importing from "extensions/core/groupNode.js" is deprecated and will be removed in v1.34. groupNode.js:2:9
[ComfyUI Notice] "extensions/core/widgetInputs.js" is an internal module, not part of the public API. Future updates may break this import. widgetInputs.js:2:9
[ComfyUI Deprecated] Importing from "scripts/ui/components/buttonGroup.js" is deprecated and will be removed in v1.34. buttonGroup.js:2:9
[ComfyUI Deprecated] Importing from "scripts/ui/components/button.js" is deprecated and will be removed in v1.34. button.js:2:9
Empty components: policy ignored components-manager.js:770:11
Trying to unset non-exist keybinding: {"commandId":"Comfy.ClearWorkflow","combo":{"key":"Backspace","ctrl":false,"alt":false,"shift":false}} keybindingStore.ts:246:15
```

### Logs

```shell

```

### Additional Context

Tried on Chrome and Firefox

┆Issue is synchronized with this [Notion page](https://www.notion.so/Issue-6766-Run-button-disabled-saying-workflow-contains-unsupported-nodes-if-anything-except-core-2b16d73d3650810292e0e41027f53517) by [Unito](https://www.unito.io)

**Comment by zlobniyshurik** [comment]
1.32.5 working for my config, 1.33.2 - not

**Comment by jovan2009** [comment]
I came to complain about the same issue. I have no "highlighted red" nodes to remove in my workflow. I will revert to previous version.

**Comment by killkrazed** [comment]
Can confirm, this is also happening to me after updating.

If you copy the workflow it is giving an error for to a new tab you can run it, but if you then try to import that workflow (eg: copying the image), it gives the error again.

There is also a very brief window after opening the workflow where you can click on the run button and it runs without issue.

ComfyUI version: 0.3.70
ComfyUI frontend version: 1.33.3
ComfyUI Manager 3.37.1

**Comment by KLL535** [comment]
Same error. All projects are broken. Nothing is glowing red.

**Comment by thelemuet** [comment]
Same here, no highlighted node. No custom node in the workflow.

**Comment by Raykosan** [comment]
Still the same problem. Don't have any "highlighted in red" nodes that need to be deleted in workflow.

<img width="1795" height="789" alt="Image" src="https://github.com/user-attachments/assets/034db00c-823c-413a-b37f-852d300018b2" />

ComfyUI version: 0.3.70
ComfyUI frontend version: 1.33.3
ComfyUI Manager 3.37.1

**Comment by SoftwareLogico** [comment]
Same here suddenly that same message

**Comment by henrikvilhelmberglund** [comment]
Until this is fixed (??? not fixed already?) you can open the devtools inspector, click on the button, and remove the `disabled` attribute in the `<button>` tag.

**Comment by PGCRT** [comment]
"Workarounds include rebuilding workflows from scratch" ROFL

**Comment by theloser** [comment]
> "Workarounds include rebuilding workflows from scratch" ROFL

I've tried this, and rebuilding your workflows works. Until you **save** your new built workflow and **reload** it, then you'll get the exact same issue again.

**Comment by christian-byrne** [comment]
This should be fixed on the latest version.

**Comment by theloser** [comment]
> This should be fixed on the latest version.

If you are referring to 1.33.5 as "latest" (which is the latest I can see) -- I would call that a half-working fix. I still get the warning about "unsupported nodes (highlighted red)" in my workflow, and there are no nodes highlighted, but at least the "Run" button isn't disabled anymore.

**Comment by christian-byrne** [comment]
True, it's a temporary half-fix. Working on the real fix now.

**Comment by viva-jinyi** [comment]
@GroxicTinch Can you provide the workflow?

**Comment by GroxicTinch** [comment]
> [@GroxicTinch](https://github.com/GroxicTinch) Can you provide the workflow?

I am not sure what you are asking for here, It happens to any and all workflows as long as it contains at least 1 custom node. 1.33.7 has semi-fixed the issue as it now, I can give you a workflow but then youd have to download whatever custom node I gave you.
Create a new workflow, add a load image going into whatever custom node you have and then into the preview image node. The workflow will show as unsupported after you refresh the tab. Delete the custom node between them and refresh the tab to see that it is now supported

**Comment by Amelia14281** [comment]
switch off "block workflow validation"

**Comment by KLL535** [comment]
Where STOP?

<img width="389" height="152" alt="Image" src="https://github.com/user-attachments/assets/981bf436-13d6-4f8d-89da-94dcda5eacfc" />

**Comment by jovan2009** [comment]
> Where STOP?
> 
> <img alt="Image" width="389" height="152" src="https://private-user-images.githubusercontent.com/189287678/518710048-981bf436-13d6-4f8d-89da-94dcda5eacfc.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQwODcwNDMsIm5iZiI6MTc2NDA4Njc0MywicGF0aCI6Ii8xODkyODc2NzgvNTE4NzEwMDQ4LTk4MWJmNDM2LTEzZDYtNGY4ZC04OWRhLTk0ZGNkYTVlYWNmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTEyNVQxNjA1NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MDg0MWMyZDFmOGJhNmUzZjNlMTdjM2Q1ZWQ3YjM2NDA4NzU0NWY0MzdjOWU2NjlkZmQyNzQyMDA0YTVhNDFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.hRyi0ImeSVZFbdmjsHc8mbJhRrfla_SuMyIb13FZ4ik">

https://github.com/Comfy-Org/ComfyUI_frontend/issues/6827#issuecomment-3566922646

**Comment by whitespace-rebel** [comment]
Version 1.34.0 fixed the problem for me.
(Debian 13, Firefox 144.0.2)

EDIT:
The error message returned after a few days, but then disappeared again. The Run button works.

EDIT_2:
Pressing R makes the error message pop up again.

**Comment by Sarashana** [comment]
> Version 1.34.0 fixed the problem for me.

I can't confirm that for myself. I still get the issue on 1.34.0. Same behavior as before. I get the warning, while nothing is highlighted red. KJnodes in use. Workflow does execute, though.

**Comment by pflky** [comment]
Same here for the latest version as of this post. The issue didn't exist at first when I updated ComfyUI with a fresh install, but then suddenly popped up later after a few restarts. Run is disabled on all workflows, even brand new ones. I don't know if installing some custom nodes triggered it to act up, but I do know that it does it on all workflows, even ones without custom nodes in them, so even trying to rebuild workflows is pointless effort. There are also no options to disable this, even rolling back the frontend didn't fix it, and rolling forward didn't fix it either.
