### ISSUE TITLE
firefox restart the page on an endless loop

### ISSUE THREAD

**Issue by michel-io** [Comfy-Org/ComfyUI_frontend#7035]
### Prerequisites

- [x] I am running the latest version of ComfyUI
- [x] I have searched existing issues to make sure this isn't a duplicate
- [x] I have tested with all custom nodes disabled ([see how](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled))

### What happened?

i recently updated the front end of my comfyui to the lastest version, the server loads well, but when the page starts to load, then reboots on an endless cicle. 

last known good version it's 1.30.6

the error happened on a firefox 145.0.2 running on windows 10

### Steps to Reproduce

1.
2.
3.

### How is this affecting you?

Crashes ComfyUI completely

### ComfyUI Frontend Version

1.32.9

### Browser

Firefox

### Console Errors

```javascript

```

### Logs

```shell

```

┆Issue is synchronized with this [Notion page](https://www.notion.so/Issue-7035-firefox-restart-the-page-on-an-endless-loop-2ba6d73d36508112b7cfc15e3c5ced81) by [Unito](https://www.unito.io)

**Comment by michel-io** [comment]
i did all the things recommended, still with the same problem, i didn't post logs because i don't see anything out of place, but still the problem persist, getting a browser log to share is difficult, because the reboot loop don't let me make screen captures

**Comment by michel-io** [comment]
my rig runs locally, and the front-end it's the latest. I install with pip install comfyui-frontend-package --upgrade

off all the logging profiles, what should i use? i tried the networking log and it's massive, like 125mb of logs just for a couple of loops, and in the end i didn't found nothing there

**Comment by michel-io** [comment]
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/950837b8-0916-4a56-a4cd-e69ae772530b" />

this it's the best that i can do, the loop don't give much time

**Comment by michel-io** [comment]
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/56106a6a-2d14-45e9-ae53-1cb3f4c3b8aa" />
filtering to xhr

**Comment by michel-io** [comment]
the last entry goes 404 and the loop happpends

**Comment by michel-io** [comment]
i just test loading the page on opera and chromium an the problem happens there too

on the backend this log happens at every loop:

Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Python312\Lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] Se ha forzado la interrupción de una conexión existente por el host remoto

**Comment by jovan2009** [comment]
I'm not sure, but your problem it's possible to be similar to this https://github.com/Comfy-Org/ComfyUI_frontend/issues/6959
Make sure you are running the latest git version of ComfyUI, my issue was solved on the server side, I think.

**Comment by michel-io** [comment]
it's not the ublock origin plugin, because disabling it does not make a difference, and the error persist even if comfyui it's added to the white list. and i am running the las git version of comfyui on a local machine

**Comment by michel-io** [comment]
in the end was a node, but the error only shows after upgrading the frontend to 1.34.5

**Comment by Darux86** [comment]
> in the end was a node, but the error only shows after upgrading the frontend to 1.34.5

which node was it?

**Comment by michel-io** [comment]
this node: [ultimate openpose editor](https://github.com/westNeighbor/ComfyUI-ultimate-openpose-editor) 

in the javascript call's for a css rule in the loading time, when the css it's not loaded yet. witch makes it fall on an endless loop. but if you call the node interface by yourself on another page(the node uses an iframe) it load without problems

there's even a pull request for this error.
