### ISSUE TITLE
Save/PreviewAudio Node DOMWidgets Rendering is Clipped by Viewport Bounds

### ISSUE THREAD

**Issue by christian-byrne** [Comfy-Org/ComfyUI_frontend#86]
The audio player widget on SaveAudio and PreviewAudio nodes are clipped by the viewport bounds. The css properties are the same between a widget that is clipped and a widget that isn't. Probably a more systemic issue than an issue with these nodes in particular.

https://github.com/Comfy-Org/ComfyUI_frontend/assets/72887196/6d13b97a-fea3-4159-a323-e89dd2f5bdd4

Using `c2e1d8f`

**Comment by huchenlei** [comment]
Yea. I think this is a fundamental/systematic issue in the `DOMWidget` design.

**Comment by christian-byrne** [comment]
> The css properties are the same between a widget that is clipped and a widget that isn't

I should have said the *inline* css properties. The original statement is most likely not true.

**Comment by pythongosssss** [comment]
Taken a look at this one, doesnt look to be related to DOMWidget but rather a quirk of the Chrome audio element.
![image](https://github.com/Comfy-Org/ComfyUI_frontend/assets/125205205/20834577-aff0-4107-86a3-4a2326480178)
The audio element is set to take up the correct width, but internally Chrome seems to be clamping the size of the element to the viewport

Setting it to a huge size, still resizes to fit the window
![image](https://github.com/Comfy-Org/ComfyUI_frontend/assets/125205205/98e3ed3c-192a-4dae-91d1-b9917fade546)

**Comment by christian-byrne** [comment]
> Taken a look at this one, doesnt look to be related to DOMWidget but rather a quirk of the Chrome audio element. ![image](https://private-user-images.githubusercontent.com/125205205/346334327-20834577-aff0-4107-86a3-4a2326480178.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0OTMyMTYsIm5iZiI6MTcyMDQ5MjkxNiwicGF0aCI6Ii8xMjUyMDUyMDUvMzQ2MzM0MzI3LTIwODM0NTc3LWFmZjAtNDEwNy04NmEzLTRhMjMyNjQ4MDE3OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQwMjQxNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZTczNDc4YmZhNzJiOWQ4MTk1NzFkNzFkYzkxNzFmMDJiNjk1MTZhN2U0MDk3MmNjYzMyZjQ1NzE4YWY4MWVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Iu7-0nWmGNtIzXML3k16j3BDSDlo3AMjnFRvERzL6bo) The audio element is set to take up the correct width, but internally Chrome seems to be clamping the size of the element to the viewport
> 
> Setting it to a huge size, still resizes to fit the window ![image](https://private-user-images.githubusercontent.com/125205205/346334462-98e3ed3c-192a-4dae-91d1-b9917fade546.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0OTMyMTYsIm5iZiI6MTcyMDQ5MjkxNiwicGF0aCI6Ii8xMjUyMDUyMDUvMzQ2MzM0NDYyLTk4ZTNlZDNjLTE5MmEtNGRhZS05MWQxLWI5OTE3ZmFkZTU0Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQwMjQxNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YWEwYzliODllNTI3ZTg0NGU5ZDllMTE1MDk3MTEzZTc5ZGEwMWMzNDY5YjFiMGY3ZjFlYjJkNjMxZWY3NDRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cU_jOnzFYHW7s-SjokhhICQbn5YUnJXqSVVyL_svBFo)

Thanks for looking at this. I tested other browsers and you're right it only happens with Chrome.

It seems that it can be fixed by setting the parent element to `overflow: visible`. Since the parent of the audio element is `body`, it might be necessary to add a container with `overflow: visible`

**Comment by melMass** [comment]
I think this was fixed by #364

**Comment by christian-byrne** [comment]
It still happens on Chrome and Edge so long as the `body` element has `overflow: hidden`
